In [11]:
import sys, os

notebook_dir = os.getcwd()
main_dir = notebook_dir[:notebook_dir.find("causal_prospective_merge")+ len("causal_prospective_merge")]
# Add the parent directory to the Python path
sys.path.append(main_dir)

from rct_data_generator import *
from causallib import datasets


data_path = '/Users/lucile/causal_info_gain/causal_prospective_merge/'
data_with_groundtruth, x, t, y = get_data(dataset='lalonde', path=data_path)


yes


In [66]:
import numpy as np
import pandas as pd

In [98]:
path_results = "/Users/lucile/causal_info_gain/causal_prospective_merge/ranking_exp/lalonde/05-18-21:07:13/resultslin.csv"

In [99]:
results  = pd.read_csv(path_results)

In [100]:
obs_closed_form = np.average(results.loc[results['Method']=='obs_closed_form'].drop(columns=['Method']), axis=0)
obs_closed_form[1:]

array([0.24444444, 0.32969697, 0.3       , 0.46666667, 0.66      ,
       1.        , 0.66666667, 0.5       ])

In [101]:
caus_closed_form = np.average(results.loc[results['Method']=='caus_closed_form'].drop(columns=['Method']), axis=0)
caus_closed_form[1:]

array([0.15111111, 0.20121212, 0.3       , 0.43333333, 0.52      ,
       1.        , 0.66666667, 0.5       ])

In [102]:
x_similarity = np.average(results.loc[results['Method']=='similarity_cov_distrib_ranking'].drop(columns=['Method']), axis=0)
x_similarity[1:]


array([-0.01333333,  0.01090909,  0.1       ,  0.3       ,  0.5       ,
        1.        ,  0.66666667,  0.5       ])

In [103]:
p_x_similarity = np.average(results.loc[results['Method']=='similarity_pscore_ranking size'].drop(columns=['Method']), axis=0)
p_x_similarity[1:]

array([0.03555556, 0.04969697, 0.3       , 0.36666667, 0.5       ,
       1.        , 0.66666667, 0.5       ])

In [104]:
sample_size = np.average(results.loc[results['Method']=='sample size'].drop(columns=['Method']), axis=0)
sample_size[1:]

array([0.08888889, 0.10787879, 0.        , 0.23333333, 0.42      ,
       0.9       , 0.6       , 0.45      ])

In [105]:
non_continuous_columns_count = x.select_dtypes(exclude=['number']).shape[1]
non_continuous_columns_count

AttributeError: 'DataFrameGroupBy' object has no attribute 'select_dtypes'

In [10]:
data_with_groundtruth

T         Y        y0        y1        x1        x2        x3  \
0    1.0  1.119462  0.049872  1.694951 -0.528957 -0.343685  1.129310   
1    0.0  1.704768  1.594767  2.019848 -1.738109 -1.803210  0.384085   
2    0.0 -0.074894 -0.728914  1.358780 -0.807992 -0.203082 -0.361140   
3    0.0 -0.822646 -0.878366  1.252129  0.390344  0.596982 -1.851590   
4    0.0 -0.548635 -0.676385  1.391063 -1.045929 -0.603114  0.011473   
..   ...       ...       ...       ...       ...       ...       ...   
742  0.0  0.427719  0.379498  1.786118 -0.007659 -0.203082 -0.361140   
743  1.0  1.074398  0.436862  1.800285  0.727782 -0.203082 -0.733752   
744  0.0 -0.604120 -0.372852  1.543007  1.182025  0.196950 -1.478977   
745  0.0 -0.038152 -0.479311  1.495240 -0.288857 -0.203082 -1.478977   
746  0.0 -0.106164 -0.181794  1.617952 -0.137443  0.596982 -0.361140   

           x4        x5        x6  ...  x16  x17  x18  x19  x20  x21  x22  \
0    0.161811 -0.316815  1.295216  ...    1    1    1    1    0    0    0   
1    2.245823 -0.629611  1.295216  ...    1    1    1    1    0    0    0   
2   -0.880195  0.809248 -0.526556  ...    1    0    1    1    0    0    0   
3   -0.880195 -0.004020 -0.857787  ...    1    0    1    1    0    0    0   
4    0.161811  0.684130 -0.360940  ...    1    1    1    1    0    0    0   
..        ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
742  0.161811 -0.316815  1.792063  ...    1    0    1    0    0    0    0   
743 -0.880195  0.809248  1.129600  ...    1    1    1    0    0    0    0   
744  0.161811  0.746689  0.467138  ...    1    1    1    0    0    0    0   
745 -0.880195  1.622516  0.467138  ...    1    1    1    0    0    0    0   
746 -0.880195  0.496453  0.135907  ...    1    1    1    0    0    0    0   

     x23  x24  x25  
0      0    0    0  
1      0    0    0  
2      0    0    0  
3      0    0    0  
4      0    0    0  
..   ...  ...  ...  
742    0    0    0  
743    0    0    0  
744    0    0    0  
745    0    0    0  
746    0    0    0  

[747 rows x 29 columns]

In [5]:
np.sum(data_with_groundtruth['T'])

173.0

In [7]:
y.head()

0    3.157727
1    4.281244
2    7.621447
3    4.015639
4   -0.240268
Name: Y, dtype: float64

In [ ]:
data['a']

0       0
1       0
2       0
3       1
4       0
       ..
4797    1
4798    1
4799    1
4800    1
4801    0
Name: a, Length: 4802, dtype: int64

In [ ]:
data = datasets.data_loader.load_acic16()
del data['descriptors']



In [ ]:
x =data['X']
x

x_1   x_3   x_4  x_5  x_6  x_7  x_8  x_9  x_10  x_11  ...  x_21_K  \
0      29   1.0   7.0   60   85    0    0    1     0     0  ...       0   
1      27   0.0   0.0   64  178    0    0    0     0     0  ...       0   
2      27   0.0   0.0   60  102    0    0    0     0     0  ...       0   
3      37   0.0   0.0   65  174    0    0    0     0     0  ...       0   
4      24  20.0  14.0   63  129    0    0    0     0     0  ...       0   
...   ...   ...   ...  ...  ...  ...  ...  ...   ...   ...  ...     ...   
4797   21   0.0   0.0   67  140    0    0    2     0     0  ...       0   
4798   24   0.0   0.0   62  130    0    0    0     0     0  ...       0   
4799   33   5.0  15.0   63  137    0    0    0     0     0  ...       0   
4800   36  10.0  22.0   60  110    0    0    1     0     0  ...       0   
4801   18   0.0   0.0   65  110    0    0    0     0     0  ...       0   

      x_21_L  x_21_M  x_21_N  x_21_O  x_21_P  x_24_B  x_24_C  x_24_D  x_24_E  
0          0       0       0       0       0       1       0       0       0  
1          0       0       0       0       0       0       0       0       1  
2          0       0       0       0       0       0       0       0       1  
3          0       0       0       0       0       0       0       0       1  
4          0       0       0       0       0       0       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...     ...  
4797       0       0       0       0       0       1       0       0       0  
4798       0       0       0       0       0       1       0       0       0  
4799       0       0       0       0       0       1       0       0       0  
4800       0       0       0       0       0       1       0       0       0  
4801       0       0       0       0       0       1       0       0       0  

[4802 rows x 79 columns]

In [ ]:
data['po'].rename(columns={'0': 'y0', '1': 'y1'})

0          1
0     3.890563   5.716108
1     5.870844   8.913574
2     7.006040  10.022676
3    -1.046089   2.952779
4    -0.478072   6.246069
...        ...        ...
4797  3.468946   5.867435
4798  4.827529   9.988942
4799  4.183918   9.469441
4800  4.684806  11.919826
4801  2.587836   7.410462

[4802 rows x 2 columns]

In [ ]:
a=data['a']
a

0       0
1       0
2       0
3       1
4       0
       ..
4797    1
4798    1
4799    1
4800    1
4801    0
Name: a, Length: 4802, dtype: int64

In [8]:
w=12

In [9]:
w>10

True